version: "3.9"

services:
  todo-list:
    container_name: todo-list
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .development.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    restart: always
  
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "65432:5432"
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: 